### ISSUE TITLE
Function VGVI_cpp not found

### ISSUE THREAD

**Issue by AlixDej** [STBrinkmann/GVI#6]
Hi everyone,

I am currently trying to compile vgvi map for a bigger area, following the example workflow of Vancouver (https://geobrinkmann.com/post/visible-greenness-exposure-index-an-example-workflow-for-the-city-of-vancouver/).

However, when I use the vgvi_from_sf function, I get an error saying: 
Error in VGVI_cpp(dsm = dsm_cpp_rast, dsm_values = dsm_vec, greenspace = greenspace_cpp_rast,  : 
  could not find function "VGVI_cpp"

I do not know how to fix this in the function vgvi_from_sf itself. Can somebody help me?

Thanks!

**Comment by STBrinkmann** [comment]
Hi, I have just rebuilt the package and it seems to work for me. Could you reinstall the GVI package and try running the code again?

Also I have updated the [blogpost](https://geobrinkmann.com/post/visible-greenness-exposure-index-an-example-workflow-for-the-city-of-vancouver/) so that it includes the new functions. This will make calculating VGVI a lot easier and faster.

**Comment by AlixDej** [comment]
Thank you for your quick respons.

I tried this, and now I get this error when calculating the VGVI:

**Comment by AlixDej** [comment]
Error in .External(list(name = "CppMethod__invoke_notvoid", address = <pointer: (nil)>, : 
NULL value passed as symbol address
